### ISSUE TITLE
Алиасы

### ISSUE THREAD

**Issue by veged** [afelix/setochka#3]
```
setochka -a "alias0, alias1, aliasN"
setochka --aliases "alias0, alias1, aliasN"
    перечисляет синонимы для использования
```

судя по коду алиасы должны быть разделены запятыми без пробелов

было бы удобно иметь стандартное поведение для перечислимых опций:

```
setochka -a alias0 -a alias1 -a aliasN
```

**Comment by afelix** [comment]
Да, в USAGE / README бага, исправил.
Вторую часть issue сделаю.

**Comment by afelix** [comment]
Done.
